apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vshn-exoscale-metrics-collector-secret
  annotations:
    kubernetes.io/service-account.name: vshn-exoscale-metrics-collector
